<?php
/**
 * Header bar template part.
 *
 * 🚫🚫🚫
 * DO NOT EDIT THIS FILE WHILE INSIDE THE PLUGIN! Changes You make will be lost when a new version
 * of the AMP plugin is released. You need to copy this file out of the plugin and put it into your
 * custom theme, for example. To learn about how to customize these Reader-mode AMP templates, please
 * see: https://amp-wp.org/documentation/how-the-plugin-works/classic-templates/
 * 🚫🚫🚫
 *
 * @package AMP
 */

/**
 * Context.
 *
 * @var AMP_Post_Template $this
 */

?>
<header id="top" class="amp-wp-header">
    <div class="amp-header-wrapper">
        <?php if ( get_theme_mod( 'mura_toggle_menu_mobile', true ) ) : ?>
            <button on="tap:sidebar-left.toggle"><span class="amp-menu">menu</span></button>
        <?php else : ?>
            <div class="no-toggle"></div>
        <?php endif; ?>
        <?php mura_site_logo( array( 'mobile' => true ) ); ?>
        <?php if ( get_theme_mod( 'mura_toggle_search_mobile', true ) ) : ?>
        <button on="tap:sidebar-right.toggle"><span class="amp-toggle-search">search</span></button>
        <?php else : ?>
            <div class="no-toggle"></div>
        <?php endif; ?>
</div>
</header>
